// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBc2XQC4Q1LvWvJJwjYGjBROn6-488FA',
    appId: '1:115570425248:android:a6fb22f1e2cc1088c2b8c5',
    messagingSenderId: '115570425248',
    projectId: 'drilly-diendev',
    databaseURL: 'https://drilly-diendev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drilly-diendev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-TAHT_M5b6OQU75pFB2wvzFKkmT0KWlM',
    appId: '1:115570425248:ios:4bbf3f45103c3e06c2b8c5',
    messagingSenderId: '115570425248',
    projectId: 'drilly-diendev',
    databaseURL: 'https://drilly-diendev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drilly-diendev.firebasestorage.app',
    iosClientId: '115570425248-989gjilmp8rcv6gbkgrm0j0tbups2llp.apps.googleusercontent.com',
    iosBundleId: 'com.diendev.drilly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfSDIqZyd8hVMxwIHtas0If-Ao1wEyT1M',
    appId: '1:115570425248:web:62b8ab6a174d38cbc2b8c5',
    messagingSenderId: '115570425248',
    projectId: 'drilly-diendev',
    authDomain: 'drilly-diendev.firebaseapp.com',
    databaseURL: 'https://drilly-diendev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drilly-diendev.firebasestorage.app',
  );

}